### ISSUE TITLE
SIQPlotteR question

### ISSUE THREAD

**Issue by ShenghisKhan** [RobinVanSchendel/SIQ#10]
Hi there,

Is there a way for SIQplotter to generate a table of frequencies of deletion outcomes that are sorted based on size, similar to the data table generated under mutation types.

**Comment by RobinVanSchendel** [comment]
Great idea. I have added a separate tab called 'Table' that allow you to view and filter all the data and to download it. You can for example select deletions here and sort on size. You can also choose which columns should be added to the output (13 columns are preselected)

In commits dffa4ce36fa9726b60d9d63f340373453c96ebe7 and 549859fc410d44adfde5244894c89019baf837e8 and already live on:

https://siq.researchlumc.nl/SIQPlotter/
