### ISSUE TITLE
SIQPlotteR question about the table 

### ISSUE THREAD

**Issue by ShenghisKhan** [RobinVanSchendel/SIQ#13]
Hi there,

Is there a way for the table to display fraction values that are normalized to 100 percent if we only want to look at certain types of mutations? For example, if we exclude the wild type fraction, can you make it so the rest of the indel fractions add up to 100? Something similar to what is done in the mutation type section.

**Comment by RobinVanSchendel** [comment]
Hi! that sounds like a good addition! I will try to add that option tomorrow

**Comment by RobinVanSchendel** [comment]
Issue has been fixed and is now live at:

https://siq.researchlumc.nl/SIQPlotter/
