### ISSUE TITLE
Copy & Paste Table Function not working MacOS

### ISSUE THREAD

**Issue by cebos** [RobinVanSchendel/SIQ#15]
Hi Robin,

Issue is as described in the title, I have a tab-delimited text file that I would like to copy and paste to automatically fill in the paths to my R1 files, alias, reference, and left and right flank info in NGS mode, but the standard MacOS paste functions don't work with the program (command v and control click don't register any kind of response from the program). I can use command v to paste all of my copied text into a single cell after double clicking and causing the blinking cursor to pop up, but of course this only pastes into a single cell and does not fill the whole table. Thank you for your time and assistance!

Cheers

**Comment by cebos** [comment]
Furthermore, I am only able to run the program on one file at a time as I can only click on and manipulate the first row.

<img width="1094" alt="Screenshot 2024-07-05 at 11 50 28 AM" src="https://github.com/RobinVanSchendel/SIQ/assets/128049810/d6764284-9989-43fe-9a41-71a39ba87207">

**Comment by RobinVanSchendel** [comment]
Hi! that is indeed inconvenient. I will try to see if I can replicate this on a mac. I unfortunately don't have one, but I will check it at a colleague. For now I have a suggestion that may work: 

Can you try to use Ctrl + V to paste your tab-separated table in SIQ? I understand that it is still inconvenient, but perhaps that helps already some for now.

**Comment by cebos** [comment]
Hi Robin,
I hadn't thought to try the windows version of the command, it works great! Thanks for your prompt response.
No need to update the program just for me, but maybe you can add a note to the usage instructions. 

Thanks again!

**Comment by RobinVanSchendel** [comment]
fixed by 9ca4902 and added to new version [v1.8](https://github.com/RobinVanSchendel/SIQ/releases/tag/v1.8)
