### ISSUE TITLE
reminder of directory not writable 

### ISSUE THREAD

**Issue by chengarthur** [RobinVanSchendel/SIQ#6]
Hi Robin, I am the one who ask for the deployable version of SIQ and I met some issues when I try to run it in windows.
I have JAVA installed and I have the administrator account . However,no matter how I change the working directory of the JAR file , it reminds me of the directory is not writable
![image](https://user-images.githubusercontent.com/25733544/180722245-ccbdb025-706f-4280-bdf0-c3874c0308ed.png)

**Comment by JasonLinjc** [comment]
I also have this issue on macOS
<img width="382" alt="image" src="https://user-images.githubusercontent.com/43600523/180775183-47d17eb3-a419-464d-80fd-78881fbdbf96.png">

**Comment by RobinVanSchendel** [comment]
Thanks for bringing this to my attention, I will check it out and let you know asap. The easiest thing to try would be to move SIQ to another directory first and then see if that works. For Windows that should definitely work, for MacOS I am not 100% sure. I will check this out tomorrow and let you know.

**Comment by RobinVanSchendel** [comment]
Commit 2828d02cd9cd25f6807b583336933717497e133d fixes this issue. I will directly deploy this in a 1.3 release to ensure people can actually use it. The issue was that a property file was checked for write access, but this was checked before the file was created and then it *obviously* does not have write access.

**Comment by RobinVanSchendel** [comment]
See: 

https://github.com/RobinVanSchendel/SIQ/releases/latest

for a fixed version
